# Generated by Django 3.2.9 on 2021-12-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_remove_todo_list_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo_list',
        ),
    ]
